spring.application.name=Veterinaria


#hibernate
spring.jpa.hibernate.ddl-auto=update
#mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/vidaanimal?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Mysql_Server


#DATOS PARA ENVIAR CORREO
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mendezbacakevin@gmail.com
spring.mail.password=dvwwlqxeafeazicc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true








